mkdir /opt/devkitpro/msys2/usr/include/lcf/
install /usr/local/lib/liblcf.dll.a  /opt/devkitpro/msys2/usr/lib
install /usr/local/bin/msys-lcf-0.dll  /opt/devkitpro/msys2/usr/bin
mkdir /opt/devkitpro/msys2/usr/include/lcf/ldb
install /usr/local/include/lcf/ldb/reader.h  /opt/devkitpro/msys2/usr/include/lcf/ldb
install /usr/local/include/lcf/ldb/chunks.h  /opt/devkitpro/msys2/usr/include/lcf/ldb
mkdir /opt/devkitpro/msys2/usr/include/lcf/lmt
install /usr/local/include/lcf/lmt/reader.h  /opt/devkitpro/msys2/usr/include/lcf/lmt
install /usr/local/include/lcf/lmt/chunks.h  /opt/devkitpro/msys2/usr/include/lcf/lmt
mkdir /opt/devkitpro/msys2/usr/include/lcf/lmu
install /usr/local/include/lcf/lmu/reader.h  /opt/devkitpro/msys2/usr/include/lcf/lmu
install /usr/local/include/lcf/lmu/chunks.h  /opt/devkitpro/msys2/usr/include/lcf/lmu
mkdir /opt/devkitpro/msys2/usr/include/lcf/lsd
install /usr/local/include/lcf/lsd/reader.h  /opt/devkitpro/msys2/usr/include/lcf/lsd
install /usr/local/include/lcf/lsd/chunks.h  /opt/devkitpro/msys2/usr/include/lcf/lsd
mkdir /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/actor.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/animation.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/animationcelldata.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/animationframe.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/animationtiming.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/attribute.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battlecommand.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battlecommands.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battleranimation.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battleranimationitemskill.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battleranimationpose.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/battleranimationweapon.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/chipset.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/class.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/commonevent.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/database.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/encounter.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/enemy.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/enemyaction.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/equipment.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/event.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/eventcommand.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/eventpage.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/eventpagecondition.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/fwd.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/item.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/learning.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/map.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/mapinfo.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/movecommand.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/moveroute.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/music.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/parameters.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/rect.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/save.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveactor.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savecommonevent.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveeasyrpgdata.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveeasyrpgtext.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveeasyrpgwindow.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveeventexecframe.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveeventexecstate.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/saveinventory.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savemapevent.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savemapeventbase.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savemapinfo.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savepanorama.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savepartylocation.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savepicture.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savescreen.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savesystem.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savetarget.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savetitle.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/savevehiclelocation.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/skill.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/sound.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/start.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/state.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/switch.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/system.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/terms.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/terrain.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/testbattler.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/treemap.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/troop.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/troopmember.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/trooppage.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/trooppagecondition.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
install /usr/local/include/lcf/rpg/variable.h  /opt/devkitpro/msys2/usr/include/lcf/rpg
mkdir /opt/devkitpro/msys2/usr/include/lcf/third_party
install /usr/local/include/lcf/third_party/span.h  /opt/devkitpro/msys2/usr/include/lcf/third_party
install /usr/local/include/lcf/third_party/string_view.h  /opt/devkitpro/msys2/usr/include/lcf/third_party
install /usr/local/include/lcf/context.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/dbarray.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/dbarrayalloc.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/dbbitarray.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/dbstring.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/encoder.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/enum_tags.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/flag_set.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/inireader.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/log_handler.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/reader_lcf.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/reader_util.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/reader_xml.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/saveopt.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/scope_guard.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/span.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/string_view.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/writer_lcf.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/writer_xml.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/include/lcf/config.h  /opt/devkitpro/msys2/usr/include/lcf
install /usr/local/lib/pkgconfig/liblcf.pc  /opt/devkitpro/msys2/usr/lib/pkgconfig
mkdir /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/lib/cmake/liblcf/liblcf-targets.cmake  /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/lib/cmake/liblcf/liblcf-targets-noconfig.cmake  /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/lib/cmake/liblcf/liblcf-config.cmake  /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/lib/cmake/liblcf/liblcf-config-version.cmake  /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/lib/cmake/liblcf/Findinih.cmake  /opt/devkitpro/msys2/usr/lib/cmake/liblcf
install /usr/local/share/mime/packages/liblcf.xml  /opt/devkitpro/msys2/usr/local/share/mime/packages
install /usr/local/bin/lcfstrings.exe  /opt/devkitpro/msys2/usr/bin
install /usr/local/bin/lcf2xml.exe /opt/devkitpro/msys2/usr/bin